// Bundles the ordered application layers (data/views → core services →
// bootstrap) into a single classic script. These layers share a global scope
// (the prototype relied on global function declarations and inline onclick
// handlers), so they must be concatenated in dependency order and emitted as a
// non-module IIFE-free classic script.
//
// We use esbuild (already a Vite dependency) for fast minification + a single
// sourcemap. The output lands in public/ so Vite serves it in dev and copies
// it verbatim on build.
import { build } from 'esbuild';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

// Dependency order matters: views/data declares the renderers and ROUTES;
// core services declare OfflineCore/LicenseCore/DataMode; bootstrap runs last
// and calls bootApp(). All cross-references resolve at call time, after every
// layer has loaded.
const LAYERS = [
  'src/core/modules.js',
  'src/core/nigeria-geo.js',
  'src/core/qc-engine.js',
  'src/core/session-compliance.js',
  'src/core/rbac.js',
  'src/core/instrument-gateway.js',
  'src/app/app.views.js',
  'src/core/api.js',
  'src/core/data-mode.js',
  'src/core/offline-core.js',
  'src/core/license-core.js',
  'src/core/service-ui.js',
  'src/app/bootstrap.js'
];

const banner = `/* LabOS by AgoroX Technologies — bundled application.
   Generated from ordered source layers. Do not edit this file directly;
   edit the sources in src/ and re-run the build. */\n`;

// Concatenate the layers, then let esbuild minify the combined source as a
// single classic script (format: 'iife' with no exports keeps top-level
// declarations effectively global once we disable the wrapper — we instead use
// no bundling of imports because there are none; the layers are plain scripts).
const combined = LAYERS
  .map((rel) => {
    const code = readFileSync(resolve(root, rel), 'utf8');
    return `/* ===== ${rel} ===== */\n${code}`;
  })
  .join('\n\n');

const tmpEntry = resolve(root, '.tmp.app.bundle.js');
writeFileSync(tmpEntry, combined);

const outDir = resolve(root, 'public');
mkdirSync(outDir, { recursive: true });

const minify = process.argv.includes('--minify');

await build({
  entryPoints: [tmpEntry],
  outfile: resolve(outDir, 'labos.bundle.js'),
  bundle: false, // no ESM imports to resolve; this is a flat classic script
  minify,
  sourcemap: true,
  target: 'es2018',
  legalComments: 'none',
  banner: { js: banner },
  logLevel: 'info'
});

// Clean up temp entry
try {
  const { unlinkSync } = await import('node:fs');
  unlinkSync(tmpEntry);
} catch {}

console.log(`[build-app] wrote public/labos.bundle.js (minify=${minify})`);

// The Supabase adapter is loaded as a standalone ES module (not part of the
// classic bundle, because it uses dynamic import() of the supabase-js CDN).
// Copy it verbatim from src/core into public/ so Vite serves and ships it.
try {
  const { copyFileSync } = await import('node:fs');
  copyFileSync(
    resolve(root, 'src/core/supabase-adapter.js'),
    resolve(outDir, 'supabase-adapter.js')
  );
  console.log('[build-app] copied supabase-adapter.js → public/');
} catch (e) {
  console.warn('[build-app] could not copy supabase-adapter.js:', e.message);
}
